openapi: 3.0.0
info:
  title: Vyser API
  description: Vyser API specifications
  version: "1.0.0"

security:
  - FirebaseJWT: []
paths:
    /provider:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "./io/CreateSeller.yaml"
            responses:
                '201':
                    description: New seller created.
                    content: 
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SuccessfulAckResponse"
                '409':
                    description: A seller associated with logged in user already exists.
                '400':
                    description: Unknown error
                    content:
                        application/json:
                            schema:
                                $ref: "../../../schema/Error.yaml"
        get:
            parameters:
              - in: query
                name: fields
                schema:
                    type: string
                    description: Array of fields to be included in the response. The array of fields will be joined into string with `,` delimeter and url encoded.
            responses:
                '200':
                    description: Seller object with only targetted fields.
                    content:
                      application/json:
                        schema:
                            type: object
                            required:
                              - fields
                              - seller
                            properties:
                                fields:
                                    type: array
                                    description: Requested fields
                                    items:
                                        type: string
                                seller:
                                    $ref: "../../../schema/internal/Seller.yaml"
                '404':
                    description: No seller associated with the account is found.
                '400':
                    description: Unknown error
                    content:
                      application/json:
                        schema:
                            $ref: "../../../schema/Error.yaml"
        put:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "./io/UpdateSeller.yaml"
            responses:
                '201':
                    description: Update completed
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SuccessfulAckResponse"
    /search/item/vision/global:
        description: Search products from the global product database using Google Cloud Vision API.
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/VisionProductSearchRequest"
            responses:
                '200':
                    description: Describes the vision search response
                    content:
                        application/json:
                            schema:
                                $ref: "./io/VisionProductSearchResponse.yaml"
                '400':
                    description: Unknown error
                    content:
                        application/json:
                            schema:
                                $ref: "../../../schema/Error.yaml"
    /search/item/vision/catalog:
        description: Search products from the sellers catalog using Google Cloud Vision API. 
        post: 
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/VisionProductSearchRequest"
            responses:
                '200':
                    description: Describes the vision search response
                    content:
                        application/json:
                            schema:
                                $ref: "./io/VisionProductSearchResponse.yaml"
                '400':
                    description: Unknown error
                    content:
                        application/json:
                            schema:
                                $ref: "../../../schema/Error.yaml"
                
        
                                

        
components:
  securitySchemes:
    SubscriberAuth:
      type: apiKey
      in: header
      name: Authorization
      description: 'Signature of message body using BAP or BPP subscriber''s signing public key. <br/><br/>Format:<br/><br/><code>Authorization : Signature keyId="{subscriber_id}|{unique_key_id}|{algorithm}",algorithm="ed25519",created="1606970629",expires="1607030629",headers="(created) (expires) digest",signature="Base64(signing string)"</code>'
    FirebaseJWT:
      type: http
      scheme: bearer
      bearerFormat: JWT 
      description: JWT using firebase authentication systm.
  schemas:
    SuccessfulAckResponse:
        type:  object
        properties:
          success:
            type: boolean
            default: true
    VisionProductSearchRequest:
        type: object
        required:
            - image
        properties:
            image:
                type: string
                description: base64 encoded image
            max_results:
                type: number
                format: int32
                default: 5
            filter:
                type: string

